- name: Push source database from controller to destination and regenerate

  hosts: "{{ TO_DB_HOST | default(TO_MW_HOST) }}"

  gather_facts: no

  tasks:

    - name: push source database dump to destination
      copy:
        src={{ CLONE_DIRECTORY }}/{{ FROM_WIKI_NAME }}-{{ FROM_DB_HOST | default(FROM_MW_HOST) }}.sql
        dest={{ CLONE_DIRECTORY }}

    - name: dump destination database
      mysql_db:
        state=dump
        name={{ TO_WIKI_NAME | default(FROM_WIKI_NAME) }}
        target={{ CLONE_DIRECTORY }}/{{ TO_WIKI_NAME | default(FROM_WIKI_NAME) }}-{{ TO_DB_HOST | default(TO_MW_HOST) }}.sql
        login_user=root
        login_password={{ MYSQL_ROOT_PASSWORD }}

    - name: remove destination database if it exists
      mysql_db:
        state=absent
        name={{ TO_WIKI_NAME | default(FROM_WIKI_NAME) }}
        login_user=root
        login_password={{ MYSQL_ROOT_PASSWORD }}

    - name: create empty destination database
      mysql_db:
        state=present
        name={{ TO_WIKI_NAME | default(FROM_WIKI_NAME) }}
        login_user=root
        login_password={{ MYSQL_ROOT_PASSWORD }}

    - name: import source database dump at destination
      mysql_db:
        state=import
        name={{ TO_WIKI_NAME | default(FROM_WIKI_NAME) }}
        target={{ CLONE_DIRECTORY }}/{{ FROM_WIKI_NAME }}-{{ FROM_DB_HOST | default(FROM_MW_HOST) }}.sql
        login_user=root
        login_password={{ MYSQL_ROOT_PASSWORD }}

- name: Push source wiki instance directory from controller to destination and unarchive

  hosts: "{{ TO_MW_HOST }}"

  gather_facts: no

  tasks:

    - name: push source wiki instance directory to destination
      copy:
        src={{ CLONE_DIRECTORY }}/{{ FROM_WIKI_NAME }}-{{ FROM_MW_HOST }}.tar.bz2
        dest={{ CLONE_DIRECTORY }}

    - name: archive destination wiki instance directory
      shell: tar cfj {{ CLONE_DIRECTORY }}/{{ TO_WIKI_NAME | default(FROM_WIKI_NAME) }}-{{ TO_MW_HOST }}.tar.bz2 -C {{ MW_INSTANCE_DIRECTORY }} {{ TO_WIKI_NAME | default(FROM_WIKI_NAME) }}

    - name: remove destination wiki instance directory
      file:
        path={{ MW_INSTANCE_DIRECTORY }}/{{ TO_WIKI_NAME | default(FROM_WIKI_NAME) }}
        state=absent

    - name: unarchive source wiki instance directory at destination (rename)
      shell: tar xfj {{ CLONE_DIRECTORY }}/{{ FROM_WIKI_NAME }}-{{ FROM_MW_HOST }}.tar.bz2 -C {{ MW_INSTANCE_DIRECTORY }} {{ FROM_WIKI_NAME }} --transform "s/^{{ FROM_WIKI_NAME }}/{{ TO_WIKI_NAME }}/"
      when: TO_WIKI_NAME is defined

    - name: unarchive source wiki instance directory at destination (no rename)
      shell: tar xfj {{ CLONE_DIRECTORY }}/{{ FROM_WIKI_NAME }}-{{ FROM_MW_HOST }}.tar.bz2 -C {{ MW_INSTANCE_DIRECTORY }} {{ FROM_WIKI_NAME }}
      when: TO_WIKI_NAME is not defined

    - name: restore destination wiki instance directory file context
      shell: restorecon -Rv {{ MW_INSTANCE_DIRECTORY }}/{{ TO_WIKI_NAME | default(FROM_WIKI_NAME) }}

    - name: run update maintenance script on new wiki
      shell: WIKI_NAME={{ TO_WIKI_NAME | default(FROM_WIKI_NAME) }} php maintenance/update.php --quick
        chdir={{ MW_CODE_DIRECTORY }}
