---
- name: adicionando CentOS6 nginx repo
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 6
  yum_repository:
    name: nginx
    description: Offiical Nginx Repository for CentOS
    baseurl: http://nginx.org/packages/centos/6/x86_64/
    gpgcheck: no
    enabled: yes


- name: adicionando CentOS7 nginx repo
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7
  yum_repository:
    name: nginx
    description: Offiical Nginx Repository for CentOS
    baseurl: http://nginx.org/packages/centos/7/x86_64/
    gpgcheck: no
    enabled: yes

- name: instalando dependencias
  package: name={{item}} state=installed
  with_items:
    - epel-release

- name: instalando nginx components
  package: name={{item}} state=installed
  with_items:
    - nginx

- name: criando nginx web diretorio
  file: path=/var/www/html state=directory owner=nginx group=nginx mode=0775 recurse=yes

- name: configurando nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=nginx group=nginx mode=0644
  notify: restart nginx

- name: configurando nginx status page
  template: src=nginx_status.conf.j2 dest=/etc/nginx/conf.d/nginx_status.conf owner=nginx group=nginx mode=0644
  notify: restart nginx

- name: configurando nginx site diretorio
  file: path=/var/www/html/{{site_name}} state=directory owner=nginx group=nginx mode=0775 recurse=yes

- name: configurando nginx site page
  template: src=nginx_site.conf.j2 dest=/etc/nginx/conf.d/{{site_name}}.conf owner=nginx group=nginx mode=0644
  notify: restart nginx

- name: iniciando serviço nginx
  service: name=nginx state=started enabled=yes
