---

- name: Adicionando repositorio NGINX CentOS7
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7
  yum_repository:
    name: nginx
    description: Offiical Nginx Repository for CentOS
    baseurl: http://nginx.org/packages/centos/7/x86_64/
    gpgcheck: no
    enabled: yes

- name: Instalando dependencias
  package: name={{item}} state=installed
  with_items:
    - epel-release

- name: Instalando nginx componentes
  package: name={{item}} state=installed
  with_items:
    - nginx

- name: Criando Diretorio Root da Aplicação
  file: path=/var/www/html state=directory owner=nginx group=nginx mode=0775 recurse=yes

- name: Configurando NGINX
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=nginx group=nginx mode=0644
  notify: restart nginx

- name: Configurando pagina de status do servidor web.
  template: src=nginx_status.conf.j2 dest=/etc/nginx/conf.d/nginx_status.conf owner=nginx group=nginx mode=0644
  notify: restart nginx

- name: Configurando Diretorio Root da Aplicação
  file: path=/var/www/html/{{site_name}} state=directory owner=nginx group=nginx mode=0775 recurse=yes

- name: Configuarando Pagina Inicial - Commons
  template: src=nginx_site.conf.j2 dest=/etc/nginx/conf.d/{{site_name}}.conf owner=nginx group=nginx mode=0644
  notify: restart nginx

- name: Iniciando serviço NGINX
  service: name=nginx state=started enabled=yes
