# Execucao
# ansible-playbook umount.yml
# Alterar para a estrutura dos servidores.

- name: Test mount and unmounts
  hosts: localhost
  remote_user: root

  tasks:

  - name: Unmount
    mount:
        path: /media/arquivos/
        state: unmounted
