- name: backup original MySQL configuration file
  shell: mv /etc/my.cnf /etc/my.cnf.orig
    creates=/etc/my.cnf.orig

- name: restore original MySQL configuration file
  shell: cp /etc/my.cnf.orig /etc/my.cnf

- name: configure MySQL to start at boot
  service:
    name=mysqld
    enabled=yes

- name: start MySQL
  service:
    name=mysqld
    state=restarted

- name: delete anonymous MySQL user
  mysql_user:
    name: ''
    host_all: yes
    state: absent

- name: remove the MySQL test database
  mysql_db:
    db=test
    state=absent

- name: stop MySQL
  service:
    name=mysqld
    state=stopped

- name: move MySQL files
  shell: mv /var/lib/mysql/* {{ MYSQL_DIRECTORY }}
    creates={{ MYSQL_DIRECTORY }}/mysql

- name: restore MySQL file context
  shell: restorecon -Rv {{ MYSQL_DIRECTORY }}

- name: copy MySQL configuration file
  template:
    src=my.cnf.j2
    dest=/etc/my.cnf
    backup=yes

- name: start MySQL
  service:
    name=mysqld
    state=started

- name: set MySQL root password
  mysql_user:
    name=root
    password={{ MYSQL_ROOT_PASSWORD }}
