- name: create root directory
  file:
    state=directory
    path={{ ROOT_DIRECTORY }}
    mode=0775
    owner=root
    group=root

- name: create backup directory
  file:
    state=directory
    path={{ CLONE_DIRECTORY }}
    mode=0775
    owner=root
    group=root

- name: create MySQL directory
  file:
    state=directory
    path={{ MYSQL_DIRECTORY }}
    mode=0700
    owner=mysql
    group=mysql
