# Install and configure snmpd

---

- hosts: web-servers
  gather_facts: yes
  vars:
  tasks:

  - name: Copiando resolv.conf
    copy: src=/static_files/resolv-dmz.conf dest=/etc/resolv.conf owner=root group=root mode=644 backup=yes
    notify: Copia Ok

