---
- name: Install Java 1.8 and some basic dependencies
  yum: name={{item}} state=present
  with_items:
   - unzip
   - java-1.8.0-openjdk

- name: Download JBoss from jboss.org
  get_url: url=http://download.jboss.org/wildfly/10.0.0.Final/wildfly-10.0.0.Final.tar.gz dest=/opt/wildfly-10.0.0.Final.tar.gz

- name: Add group "wildfly"
  group: name=wildfly

- name: Add user "wildfly"
  user: name=wildfly group=wildfly shell=/sbin/nologin createhome=no
  
- name: Extract archive
  unarchive:
          src: /opt/wildfly-10.0.0.Final.tar.gz
          dest: /opt/
          remote_src: yes

- name: Cria Link Simbolico
  file:
          src=/opt/wildfly-10.0.0.Final
          dest=/opt/wildfly
          state=link
  
- name: Altera Owner do diretorio
  command: chown -R wildfly:wildfly /opt/wildfly/
    

- name: Copying standalone.xml configuration file
  template: src=standalone.xml dest=/opt/wildfly/standalone/configuration/
  

- name: Change ownership of JBoss installation
  file: path=/opt/wildfly/ owner=wildfly group=wildfly state=directory recurse=yes

- name: Configurando o systemd
  file:
          path: /etc/wildfly
          state: directory

- name: Copiando o arquivo de config.
  copy: src=wildfly.conf dest=/etc/wildfly  

- name: Copiando o arquivo de config.
  copy: src=wildfly.service dest=/etc/systemd/system
    
- name: Copy the init script
  copy: src=launch.sh dest=/opt/wildfly/bin mode=0755
  
  
- name: Permissao para o arquivo ser executado.
  command: chmod +x /opt/wildfly/bin/launch.sh
    
- name: Enable JBoss to be started at boot
  command: systemctl enable wildfly.service
  
- name: Enable JBoss to be started at boot
  command: systemctl start wildfly.service 
