---
- hosts: all 
  tasks:
    - name: install git package
      apt:
        name: git

    - name: install git package
      apt:
        name: python

    - name: Download de artefatos do repositorio GIT 
      git: 
        repo: "http://{{ gituser | urlencode }}:{{ gitpassword | urlencode }}@gitlab.turismo.gov.br/infra/PEA.git"
        dest: /opt/deploy/PEA
        version: pea_deploy_v2.13
